name: foodtracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.1
  logging: ^1.2.0
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  share_plus: ^10.0.2

  # UI moderna
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  animations: ^2.0.11
  sqflite: ^2.4.2
  drift: ^2.29.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.10.2
  flutter_launcher_icons: ^0.13.1

# Configuração correta do Flutter Launcher Icons


flutter:
  uses-material-design: true
